# ref: https://github.com/actions/runner-images
name: amd64 Linux

on: [push, pull_request, workflow_dispatch]

  # Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
      fail-fast: false
    name: Linux • Bazel • Python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install Bazel
        run: |
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt-get update
          sudo apt-get install bazel
      - name: Check bazel
        run:  bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          ...
      - name: Test
        run: >
          bazel test
          -c opt
          --test_output=errors
          ...
