name: amd64 macOS

on: [push, pull_request]

jobs:
  bazel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Bazel
      run: |
        brew update
        #brew install bazel
    - name: Check Bazel
      run: bazel version
    - name: Build
      run: bazel build --cxxopt=-std=c++17 --test_output=errors ...
    - name: Test
      run: bazel test --cxxopt=-std=c++17 --test_output=errors ...
