# ref: https://github.com/actions/runner-images
name: amd64 macOS

on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        option: [
          '--action_env=BAZEL_CXXOPTS="-std=c++17"',
          '--cxxopt="-std=c++17"']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set Java to OpenJDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check mvn
        run: mvn --version
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install Bazel
        run: |
          brew update
          brew unlink bazelisk
          brew install bazel
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          ${{ matrix.option }}
          --subcommands=true
          ...
      - name: Test
        run: >
          bazel test
          -c opt
          ${{ matrix.option }}
          --test_output=all
          ...
