# ref: https://github.com/actions/runner-images
name: amd64 MacOS

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    name: MacOS • Bazel • Python-${{ matrix.python-version }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Java to OpenJDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check mvn
        run: mvn --version
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install Bazel
        run: |
          brew update
          brew unlink bazelisk
          brew install bazel
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          ...
      - name: Test
        run: >
          bazel test
          -c opt
          --test_output=errors
          ...
