name: amd64 Windows

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  bazel:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Bazel
      run: choco install bazel
    - name: Check Bazel
      run: bazel version
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Check mvn
      run: mvn --version
    - name: Build
      run: bazel build -c opt --cxxopt="-std:c++17" --subcommands=true ...
    - name: Inspect
      run: ls -R bazel-out
    - name: Test
      run: bazel test -c opt --cxxopt="-std:c++17" --test_output=errors ...
