# ref: https://github.com/actions/runner-images
name: amd64 Linux Bazel

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python: [
          #{version: '3.9'},
          #{version: '3.10'},
          {version: '3.11'},
          {version: '3.12'},
        ]
      fail-fast: false
    name: Linux•Bazel•Py${{matrix.python.version}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check Java
        run: java -version
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python.version}}
      - name: Check Python
        run: |
          python --version
          python -m platform
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{github.workflow}}
          repository-cache: true
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          //...
      - name: Test
        run: >
          bazel test
          -c opt
          --subcommands=pretty_print
          --test_output=errors
          //...

  amd64_linux_bazel:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v5
