# ref: https://github.com/docker-library/official-images
name: riscv64 Docker Bazel

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      matrix:
        platform: [arm64]
        distro: [
          # almalinux,
          alpine,
          debian, # currently only unstable not latest
          # fedora,
          # opensuse,
          # rockylinux,
          # ubuntu,
        ]
      fail-fast: false
    name: ${{matrix.platform}}•${{matrix.distro}}•Bazel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Check docker
        run: |
          docker version
          docker info
          docker buildx ls
      - name: Build env image
        run: make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_env
      - name: Build devel image
        run: make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_devel
      - name: Build project
        run: make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_build
      - name: Test project
        run: make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_test

  riscv64_docker_bazel:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v5
